# Generated by Django 5.0 on 2023-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_otp_enabled_user_otp_secret_user_otp_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_forgot_pass",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
