# Generated by Django 5.0 on 2023-12-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_otp_forgot_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_forgot_pass_validated",
            field=models.BooleanField(default=False),
        ),
    ]
