# Generated by Django 5.0 on 2023-12-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("shared", "Shared"),
                ],
                default="private",
                max_length=10,
            ),
        ),
    ]
