# Generated by Django 5.0 on 2023-12-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0004_diaryentry_privacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("shared", "Shared"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
