# Generated by Django 5.0 on 2023-12-21 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0005_alter_diaryentry_privacy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
